name: Update Header Graphics

on:
  schedule:
    - cron: '0 */8 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-header:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install svgwrite pillow --no-cache-dir
        
    - name: Verify Python environment
      run: |
        python --version
        pip list
        
    - name: Generate header graphics
      run: |
        cd ${{ github.workspace }}
        python scripts/generate_svg.py
        ls -la *.svg
        
    - name: Configure Git
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
    - name: Commit and push graphics
      run: |
        git add header.svg analytics.svg || echo "No SVG files to add"
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        else
          git status
          git commit -m "🎨 Update AI profile graphics - $(date '+%Y-%m-%d %H:%M UTC')

        ✨ Header visualization updated
        📊 Analytics dashboard refreshed  
        🤖 Autonomous generation active" || echo "Commit failed"
          git push origin main || echo "Push failed"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
