name: Update Profile SVGs

on:
  schedule:
    # Update SVGs every 6 hours
    - cron: '0 */6 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-svg:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install svgwrite
        
    - name: Generate SVGs
      run: |
        python scripts/generate_svg.py
        
    - name: Commit and push SVGs
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add header.svg analytics.svg
        git diff --staged --quiet || git commit -m "🤖 Update profile SVGs - $(date '+%Y-%m-%d %H:%M')"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}