name: VertexAutoGPT Profile Updates

on:
  schedule:
    # Update every 4 hours to show active development
    - cron: '0 */4 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-vertex-profile:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install svgwrite pillow
        
    - name: Generate VertexAutoGPT header
      run: |
        python scripts/generate_vertex_header.py
        
    - name: Commit and push updates
      run: |
        git config --local user.email "vertex-agent@github.com"
        git config --local user.name "VertexAutoGPT Agent"
        git add header.svg
        git diff --staged --quiet || git commit -m "🤖 VertexAutoGPT Status Update - $(date '+%Y-%m-%d %H:%M UTC')

        🧠 Vector Memory: Optimized
        🔧 Tool Router: Active
        ☁️  GCP Infrastructure: Running
        ⚡ Agent Development: In Progress"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}